// Generated by CoffeeScript 1.6.3
var direquire, exec, fs, path;

fs = require('fs');

path = require('path');

exec = require('child_process').exec;

direquire = function(dir) {
  var body, filepath, key, list, modules, name, val, _i, _len, _ref, _ref1, _ref2;
  if ('/' !== dir.substr(0, 1)) {
    dir = path.resolve(dir);
  }
  modules = {};
  if (!fs.existsSync(dir)) {
    throw new Error("ENOTEXISTS " + dir);
    return modules = {};
  }
  _ref = fs.readdirSync(dir);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    list = _ref[_i];
    filepath = path.join(dir, list);
    if (fs.statSync(filepath).isDirectory()) {
      if (!(path.basename(filepath)).match(/^\./)) {
        modules[path.basename(filepath)] = direquire(filepath);
      }
    } else if (/\.(coffee|js|json)/.test(filepath)) {
      _ref1 = require(filepath);
      for (name in _ref1) {
        body = _ref1[name];
        if (typeof modules[name] !== 'undefined') {
          _ref2 = modules[name];
          for (key in _ref2) {
            val = _ref2[key];
            body[key] = val;
          }
        }
        modules[name] = body;
      }
    }
  }
  return modules;
};

module.exports = direquire;
